In [2]:
# 1. Import dependencies
import torch


![computing graph](./comp-graph.png)
> Check the following [page](https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html#tensors-functions-and-computational-graph) for the computing graph .

In [14]:
# 2. define one-layer neural network
x = torch.ones(5) # input  tensor
y = torch.zeros(3) # expected output

w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)

z = torch.matmul(x, w)+b

loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss

tensor(0.5296, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [4]:
# 3. compute gradient

print(w.grad)
print(b.grad)
loss.backward()
print(w.grad)
print(b.grad)

None
None
tensor([[0.0126, 0.0922, 0.0358],
        [0.0126, 0.0922, 0.0358],
        [0.0126, 0.0922, 0.0358],
        [0.0126, 0.0922, 0.0358],
        [0.0126, 0.0922, 0.0358]])
tensor([0.0126, 0.0922, 0.0358])


In [12]:
# APPENDIX
# Pytorch Matrix Multiple examples



# Define two matrices
tensor1 = torch.tensor([
    [1, 2], 
    [3, 4]
])
tensor2 = torch.tensor([
    [5, 6, 7], 
    [7, 8, 9]
])

print(f'tensor1 . tensor 2 : {tensor1.shape} . { tensor2.shape }')

# Matrix multiplication
result = torch.matmul(tensor1, tensor2)
print(result)

tensor1 . tensor 2 : torch.Size([2, 2]) . torch.Size([2, 3])
tensor([[19, 22, 25],
        [43, 50, 57]])
