In [2]:
import numpy as np



# Example 1 - 1D matrix dot product

In [3]:

# Define two vectors (1D arrays) as lists
vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

# Compute the dot product
# The formula is (1*4) + (2*5) + (3*6) = 4 + 10 + 18 = 32
result = np.dot(vector1, vector2)

# Print the result
print(f"The dot product is: {result}")

The dot product is: 32


# Example 2 - 2D matrix dot product

Let’s multiply a $2 \times 2$ matrix by a $2 \times 2$ matrix:

$$A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, \quad B = \begin{bmatrix} e & f \\ g & h \end{bmatrix}$$
The resulting matrix $C$ is:

$$C = A \cdot B = \begin{bmatrix} (a \cdot e + b \cdot g) & (a \cdot f + b \cdot h) \\ (c \cdot e + d \cdot g) & (c \cdot f + d \cdot h) \end{bmatrix}$$



In [4]:


A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Using the @ operator (recommended)
result = A @ B

# Or using np.dot()
# result = np.dot(A, B)

print(result)
# Output:
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]


# Example 3 - 2D matrix dot product

- 2*3 matrix
- 3*2 matrix

dot product

$$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}, \quad B = \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix}$$



In [ ]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

B = np.array([[7, 8], 
              [9, 10],
              [11, 12]])

A@B
# 1*7 + 2*9 + 3*11 = 7+18+33=58


array([[ 58,  64],
       [139, 154]])