# Introduction
This the **./01-brigram** notebook.

A probability distribution, that is based on bigram counts, is used to generate name predictions.

In this notebook.

A a neural network approache will be used.

And this notebook is based on this [video](https://youtu.be/PaCmpygFfXo?si=jlreZYqCOdqHNMwA&t=5177).

In [6]:
# Load data 

words = open('./data/names.txt', 'r').read().splitlines()

len(words)

32033

In [7]:


chars = sorted(list(set(''.join(words))))

stoi = { s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = { i:s for s, i in stoi.items()}

In [11]:
import torch

# Create the training set of bigram (x,y)

xs, ys = [], []

for w in words[:1]:
    
    chs = ['.'] + list(w) + ['.']
    
    # zip() generate the [2-consecutive characters]
    for ch1, ch2  in zip(chs, chs[1:]):

        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1, ch2)

        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)


. e
e m
m m
m a
a .


In [13]:
xs, ys

(tensor([ 0,  5, 13, 13,  1]), tensor([ 5, 13, 13,  1,  0]))

In [25]:
# Randomly initialize 27 neuron weights, each neuron receives 27 inputs
g = torch.Generator().manual_seed(2147483647)

W = torch.randn((27, 27), generator=g)
W.shape, W[0,:]

(torch.Size([27, 27]),
 tensor([ 1.5674, -0.2373, -0.0274, -1.1008,  0.2859, -0.0296, -1.5471,  0.6049,
          0.0791,  0.9046, -0.4713,  0.7868, -0.3284, -0.4330,  1.3729,  2.9334,
          1.5618, -1.6261,  0.6772, -0.8404,  0.9849, -0.1484, -1.4795,  0.4483,
         -0.0707,  2.4968,  2.4448]))

In [28]:
import torch.nn.functional as F

xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
logits = xenc @ W     # Semantics: log-counts
counts = logits.exp() # Semantics: counts, equivalent to N

probs = counts / counts.sum(1, keepdims=True) # probability for next character
probs

(tensor([[0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
          0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
          0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459],
         [0.0290, 0.0796, 0.0248, 0.0521, 0.1989, 0.0289, 0.0094, 0.0335, 0.0097,
          0.0301, 0.0702, 0.0228, 0.0115, 0.0181, 0.0108, 0.0315, 0.0291, 0.0045,
          0.0916, 0.0215, 0.0486, 0.0300, 0.0501, 0.0027, 0.0118, 0.0022, 0.0472],
         [0.0312, 0.0737, 0.0484, 0.0333, 0.0674, 0.0200, 0.0263, 0.0249, 0.1226,
          0.0164, 0.0075, 0.0789, 0.0131, 0.0267, 0.0147, 0.0112, 0.0585, 0.0121,
          0.0650, 0.0058, 0.0208, 0.0078, 0.0133, 0.0203, 0.1204, 0.0469, 0.0126],
         [0.0312, 0.0737, 0.0484, 0.0333, 0.0674, 0.0200, 0.0263, 0.0249, 0.1226,
          0.0164, 0.0075, 0.0789, 0.0131, 0.0267, 0.0147, 0.0112, 0.0585, 0.0121,
          0.0650, 0.0058, 0.0208, 0.0078, 0.0133, 0.0203, 0.1204, 0.0469, 0.0126],
         [0.