In [1]:
import numpy as np

In [2]:
# 1. 定义 7x7 的输入图像
input_image = np.array([
    [10, 10, 10, 100, 100, 100, 100],
    [10, 10, 10, 100, 100, 100, 100],
    [10, 10, 10, 100, 100, 100, 100],
    [10, 10, 10, 100, 100, 100, 100],
    [10, 10, 10, 100, 100, 100, 100],
    [10, 10, 10, 100, 100, 100, 100],
    [10, 10, 10, 100, 100, 100, 100]
], dtype=np.float32)

In [4]:
# 2. 定义 Sobel 卷积核 (Gx 和 Gy)
Gx = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
], dtype=np.float32)

Gy = np.array([
    [-1, -2, -1],
    [ 0,  0,  0],
    [ 1,  2,  1]
], dtype=np.float32)

In [5]:
# 3. 实现自定义的带步长（Stride）二维卷积函数
def conv2d_stride(image, kernel, stride=2):
    h, w = image.shape
    kh, kw = kernel.shape
    
    # 计算无填充（Padding=0）时的输出尺寸
    out_h = (h - kh) // stride + 1
    out_w = (w - kw) // stride + 1
    
    output = np.zeros((out_h, out_w), dtype=np.float32)
    
    for i in range(out_h):
        for j in range(out_w):
            # 根据步长计算在输入图像中的起始位置
            r_start = i * stride
            c_start = j * stride
            
            # 提取 3x3 局部窗口
            window = image[r_start:r_start+kh, c_start:c_start+kw]
            
            # 点乘并求和
            output[i, j] = np.sum(window * kernel)
            
    return output

In [6]:
# 4. 执行计算（设置 stride=2）
output_gx = conv2d_stride(input_image, Gx, stride=2)
output_gy = conv2d_stride(input_image, Gy, stride=2)

print("水平梯度 Gx 输出 (3x3):")
print(output_gx)

print("\n垂直梯度 Gy 输出 (3x3):")
print(output_gy)

水平梯度 Gx 输出 (3x3):
[[  0. 360.   0.]
 [  0. 360.   0.]
 [  0. 360.   0.]]

垂直梯度 Gy 输出 (3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
