In [2]:
import numpy as np

In [11]:
# 1. 模拟一个 7x7 的 3通道 RGB 图像 (Shape: 7 x 7 x 3)
# 假设左侧偏暗，右侧偏亮
input_rgb = np.zeros((7, 7, 3), dtype=np.float32)
input_rgb[:, :3, :] = 10.0   # 左侧暗
input_rgb[:, 3:, :] = 100.0  # 右侧亮

input_rgb[:,:,0]


array([[ 10.,  10.,  10., 100., 100., 100., 100.],
       [ 10.,  10.,  10., 100., 100., 100., 100.],
       [ 10.,  10.,  10., 100., 100., 100., 100.],
       [ 10.,  10.,  10., 100., 100., 100., 100.],
       [ 10.,  10.,  10., 100., 100., 100., 100.],
       [ 10.,  10.,  10., 100., 100., 100., 100.],
       [ 10.,  10.,  10., 100., 100., 100., 100.]], dtype=float32)

In [12]:
# 2. 定义单通道的 Sobel 算子 Gx
Gx = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
], dtype=np.float32)

In [ ]:
# 3. 实现 3 通道带步长的卷积函数
def conv2d_3ch_stride(image, kernel, stride=2):
    h, w, c = image.shape
    kh, kw = kernel.shape
    
    out_h = (h - kh) // stride + 1
    out_w = (w - kw) // stride + 1
    
    output = np.zeros((out_h, out_w), dtype=np.float32)
    
    for i in range(out_h):
        for j in range(out_w):
            r_start = i * stride
            c_start = j * stride
            
            # 提取 3x3x3 的局部空间块
            window = image[r_start:r_start+kh, c_start:c_start+kw, :]
            
            # 遍历每个通道进行卷积，并将结果累加
            channel_sum = 0.0
            for ch in range(c):
                channel_sum += np.sum(window[:, :, ch] * kernel)
                
            output[i, j] = channel_sum
            
    return output

In [14]:
# 4. 执行计算
output_gx_rgb = conv2d_3ch_stride(input_rgb, Gx, stride=2)

print("3 通道输入下的水平梯度 Gx 输出 (3x3):")
print(output_gx_rgb)

3 通道输入下的水平梯度 Gx 输出 (3x3):
[[   0. 1080.    0.]
 [   0. 1080.    0.]
 [   0. 1080.    0.]]
