In [2]:
# Import dependencies
import torch

Check the following page for the computing graph .
- [Automatic Differentiation with torch.autograd](https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html#tensors-functions-and-computational-graph)

In [30]:
# define one-layer neural network
x = torch.ones(5) # input  tensor
y = torch.zeros(3) # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [31]:
print(w.grad)
print(b.grad)
loss.backward()
print(w.grad)
print(b.grad)

None
None
tensor([[0.3322, 0.0409, 0.3198],
        [0.3322, 0.0409, 0.3198],
        [0.3322, 0.0409, 0.3198],
        [0.3322, 0.0409, 0.3198],
        [0.3322, 0.0409, 0.3198]])
tensor([0.3322, 0.0409, 0.3198])


In [12]:
# Pytorch Matrix Multiple examples



# Define two matrices
tensor1 = torch.tensor([
    [1, 2], 
    [3, 4]
])
tensor2 = torch.tensor([
    [5, 6, 7], 
    [7, 8, 9]
])

print(f'tensor1 . tensor 2 : {tensor1.shape} . { tensor2.shape }')

# Matrix multiplication
result = torch.matmul(tensor1, tensor2)
print(result)

tensor1 . tensor 2 : torch.Size([2, 2]) . torch.Size([2, 3])
tensor([[19, 22, 25],
        [43, 50, 57]])
